print("what is your sign?")
sign = input()
if sign == "Aries":
    print("\\         /")
    print(" \\       /")
    print("  \\     /")
    print("   \\   /")
    print("    \\ /")
    print("     v")
if sign == "Taurus":
    print("  )(")
    print("  () ")
if sign == "Leo":
    print(" _  ")
    print(" ()")
    print(" 0 )")
    print("   (")
if sign == "Gemini":
    print(" \\       /")
    print("  ------- ")
    print(" |       |")
    print(" |       |")
    print(" |       |")
    print("  ------- ")
    print(" /        \\")
if sign == "Cancer":
    print(" (       )  ")
    print("  )     (  ")
    print("   -----  ")
    print("  |     |")
    print("--|     |--")
    print("  |     |")
    print("   -----  ")
if sign == "Virgo":
    print("  --  --  --")
    print(" |  ||  ||  |")
    print(" |  ||  ||  |--")
    print(" |  ||  ||  |   )")
    print(" |  ||  ||  |  /")
    print("            | /")
    print("             /")
    print("            ()")
if sign == "Libra":
    print("      /\\")
    print("     /  \\")
    print("    /    \\")
    print("    -------")
    print("    \\      |")
    print("     |      \\")
if sign == "Scorpio":
    print("       /\\")
    print("       \\")
    print("        \\")
    print("         \\")
    print("         \\\\/")
if sign == "Sagittarius":
    print("      /\\")
    print("      /")
    print("     /")
    print("    /")
if sign == "Capricorn":
    print("   \\/--")
    print("    |   |")
    print("        ()")
    print("        /")
if sign == "Aquarius":
    print("               /")
    print("              /")
    print("             /\\")
    print("           --  \\")
    print("           |     \\")
    print("           \\     ")
    print("            |      ")
    print("            \\  ")
if sign == "Pisces":
    print(" )-( ")